/**
 * The descriptive part of an expedition.
 *
 * Metadata is everything a person needs to decide whether an expedition suits
 * their class. It never affects how the game is played. The engine may ignore
 * this whole section.
 */

import type { IntRange, IsoTimestamp, MediaRef } from './common.ts';

/** Where an expedition is meant to be played. */
export type ExpeditionSetting = 'indoor' | 'outdoor' | 'mixed';

/** How an expedition came to exist. */
export type AuthoringSource =
  /** Built by hand in the Studio. */
  | 'studio'
  /** Built by a teacher in the Creator web app. */
  | 'creator-web'
  /** Generated by the AI builder. */
  | 'ai'
  /** Copied from a template. */
  | 'template'
  /** Imported from an activity the school already had. */
  | 'import';

/** Who made an expedition, and when. */
export interface AuthoringInfo {
  /** The organisation that owns the expedition. */
  organisationId: string;
  /** The account that first created it. */
  createdBy: string;
  createdAt: IsoTimestamp;
  /** The account that last changed it. */
  updatedBy: string;
  updatedAt: IsoTimestamp;
  source: AuthoringSource;
  /** Set when the expedition began life as a copy of a template (EXPD-060). */
  templateId?: string;
}

/** The descriptive part of an expedition. */
export interface ExpeditionMetadata {
  /** The name shown to teachers and students. Required, and never empty. */
  title: string;
  /** One or two sentences describing the expedition. */
  summary: string;
  /** The full description, shown on the expedition's own page. */
  description?: string;
  /**
   * The language the player-facing text is written in, as a BCP 47 tag.
   *
   * Example: `en-GB`. One expedition is written in one language. Translating
   * an expedition means making another expedition.
   */
  locale: string;
  /** The ages the expedition is written for, in years. */
  ageRange: IntRange;
  /** How long a team is expected to take, in minutes. */
  expectedDurationMinutes: IntRange;
  /** School subjects the expedition covers. May be empty. */
  subjects: string[];
  /** Free-form labels used for search. May be empty. */
  tags: string[];
  setting: ExpeditionSetting;
  /** The image shown on the expedition card. */
  coverMedia?: MediaRef;
  authoring: AuthoringInfo;
}

/** Every expedition setting. */
export const EXPEDITION_SETTINGS = ['indoor', 'outdoor', 'mixed'] as const;

/** Every authoring source. */
export const AUTHORING_SOURCES = [
  'studio',
  'creator-web',
  'ai',
  'template',
  'import',
] as const;
