-- EXPD-003 — PostgreSQL core data model.
--
-- The first migration. It creates every table the platform stores, plus the
-- enum types and indexes they need. Nothing here is behaviour: no triggers
-- that score, no rules that decide when a team may move on. Those belong to
-- the engine tickets (EXPD-009 to EXPD-015) and the API tickets
-- (EXPD-016 to EXPD-023).
--
-- Two ideas run through the whole file.
--
-- 1. The Expedition Definition (EXPD-002) is the contract. A published
--    expedition is stored whole, as one JSONB document, in
--    `expedition_version.definition`. That document is the source of truth,
--    and the engine can run an expedition from it alone.
--
-- 2. `mission_instance`, `mission_node` and `hint` are a flat copy of the
--    parts of that document other tables have to point at. A mission attempt
--    needs a real foreign key to the mission it is an attempt of, and a
--    string buried in a JSONB document cannot be one. EXPD-017 keeps the copy
--    in step with the document when a version is written.
--
-- Requires PostgreSQL 14 or newer. `gen_random_uuid()` has been built in
-- since 13, so no extension is installed.

BEGIN;

-- ---------------------------------------------------------------------------
-- Conventions
-- ---------------------------------------------------------------------------
--
-- Primary keys      `uuid`, generated by the database.
-- Times             `timestamptz`. The database never stores a local time.
-- Durations         whole seconds, named `*_seconds`, matching EXPD-002.
-- Points            whole numbers. EXPD-002 has no fractional scores.
-- Enum values       kebab-case, copied from the EXPD-002 union types where
--                   one exists. `subscription_status` is the one exception:
--                   it uses Stripe's own values, because that is the contract
--                   with Stripe (EXPD-068).
-- Tenancy           every table an organisation owns carries
--                   `organisation_id`, even when it could be reached through
--                   a parent. EXPD-004 and EXPD-005 filter on that column.
-- Naming            the table for a user is `app_user`. `user` is a reserved
--                   word in SQL, and `SELECT user` already means something
--                   else in PostgreSQL.

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- Keeps `updated_at` honest. Attached below to every table that has one.
CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION set_updated_at() IS
  'Trigger function. Sets updated_at to now() on every UPDATE.';

-- ---------------------------------------------------------------------------
-- Enum types
-- ---------------------------------------------------------------------------
--
-- Only types a column actually uses are created here. The parts of EXPD-002
-- that stay inside the definition document — progression mode, start and end
-- mode, leaderboard settings — have no column, so they have no type.
--
-- To add a value later: ALTER TYPE <name> ADD VALUE '<value>';

-- From EXPD-002 `ExpeditionStatus`.
CREATE TYPE expedition_status AS ENUM ('draft', 'published', 'archived');

-- From EXPD-002 `AuthoringSource`.
CREATE TYPE authoring_source AS ENUM (
  'studio', 'creator-web', 'ai', 'template', 'import'
);

-- From EXPD-002 `VerificationMode`.
CREATE TYPE verification_mode AS ENUM (
  'automatic', 'teacher', 'automatic-with-review'
);

-- From EXPD-002 `ExpeditionNodeKind`.
CREATE TYPE expedition_node_kind AS ENUM (
  'start', 'mission', 'checkpoint', 'finish'
);

-- From EXPD-002 `LocationConstraint['onPoorAccuracy']`.
CREATE TYPE poor_accuracy_action AS ENUM ('block', 'warn', 'ignore');

-- From EXPD-002 `MediaRef['kind']`.
CREATE TYPE media_kind AS ENUM ('image', 'audio', 'video', 'document');

CREATE TYPE organisation_status AS ENUM ('active', 'suspended', 'closed');

CREATE TYPE user_status AS ENUM ('invited', 'active', 'suspended', 'deactivated');

CREATE TYPE membership_role AS ENUM (
  'owner', 'admin', 'creator', 'teacher', 'member'
);

CREATE TYPE membership_status AS ENUM ('invited', 'active', 'revoked');

-- Stripe's own subscription statuses, spelled exactly as Stripe spells them
-- so that a webhook value can be stored without translation (EXPD-068).
CREATE TYPE subscription_status AS ENUM (
  'trialing', 'active', 'past_due', 'canceled',
  'incomplete', 'incomplete_expired', 'unpaid', 'paused'
);

CREATE TYPE mission_type_status AS ENUM ('draft', 'published', 'deprecated');

CREATE TYPE mission_template_status AS ENUM ('draft', 'published', 'archived');

-- The states one run of an expedition passes through. EXPD-019 owns which
-- change is allowed to follow which; this type only lists the states.
CREATE TYPE session_status AS ENUM (
  'scheduled', 'lobby', 'running', 'paused', 'ended', 'cancelled'
);

CREATE TYPE team_status AS ENUM (
  'forming', 'ready', 'playing', 'finished', 'withdrawn'
);

CREATE TYPE participant_status AS ENUM (
  'invited', 'joined', 'active', 'left', 'removed'
);

-- The states one try at a mission passes through. EXPD-010 owns the
-- transitions between them.
CREATE TYPE attempt_status AS ENUM (
  'open', 'submitted', 'awaiting-review',
  'succeeded', 'failed', 'expired', 'skipped'
);

CREATE TYPE submission_status AS ENUM (
  'pending', 'needs-review', 'accepted', 'rejected'
);

-- A blob is written before it is confirmed, because the upload itself happens
-- against a signed URL and not against the API (EXPD-021).
CREATE TYPE media_status AS ENUM ('pending', 'ready', 'failed', 'deleted');

CREATE TYPE inventory_item_kind AS ENUM (
  'hint-token', 'badge', 'collectible', 'key', 'custom'
);

CREATE TYPE qr_marker_status AS ENUM ('active', 'retired');

CREATE TYPE ar_asset_kind AS ENUM (
  'model', 'image-target', 'plane-anchor', 'effect'
);

-- Why points moved. The middle seven are the EXPD-002 `ScoringRuleType`
-- values one for one. The rest cover the ways points move without a rule.
CREATE TYPE score_event_reason AS ENUM (
  'mission-complete',
  'partial-credit',
  'speed-bonus',
  'first-to-complete-bonus',
  'streak-bonus',
  'completion-bonus',
  'hint-penalty',
  'attempt-penalty',
  'late-penalty',
  'manual-adjustment'
);

CREATE TYPE audit_actor_kind AS ENUM ('user', 'participant', 'system', 'service');

-- ---------------------------------------------------------------------------
-- Organisation, user, membership, subscription
-- ---------------------------------------------------------------------------

-- A school, a trust or a company. The tenant boundary. Nothing an
-- organisation owns is ever visible to another one (EXPD-004, EXPD-005).
CREATE TABLE organisation (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name         text NOT NULL CHECK (length(btrim(name)) > 0),
  -- Used in URLs and join links. Compared without case.
  slug         text NOT NULL CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  status       organisation_status NOT NULL DEFAULT 'active',
  -- The timezone the organisation works in, as an IANA name such as
  -- `Europe/London`. Used to show a teacher a start time in their own day.
  -- Stored times stay in UTC.
  timezone     text NOT NULL DEFAULT 'UTC',
  -- Default language for the organisation's own screens, as a BCP 47 tag.
  locale       text NOT NULL DEFAULT 'en-GB',
  settings     jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX organisation_slug_key ON organisation (lower(slug));

COMMENT ON TABLE organisation IS
  'A tenant. Every other organisation-owned row carries its id.';

-- One person's account. A user is not tied to one organisation: the same
-- teacher may work for two schools, which is what `membership` is for.
--
-- There is no password or token column here on purpose. How a person proves
-- who they are is EXPD-004.
CREATE TABLE app_user (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email         text NOT NULL CHECK (position('@' IN email) > 1),
  display_name  text NOT NULL CHECK (length(btrim(display_name)) > 0),
  status        user_status NOT NULL DEFAULT 'invited',
  locale        text NOT NULL DEFAULT 'en-GB',
  last_seen_at  timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX app_user_email_key ON app_user (lower(email));

COMMENT ON TABLE app_user IS
  'A person with an account. Named app_user because user is a reserved word.';

-- What one person may do inside one organisation. A person with accounts in
-- two organisations has two rows here and one row in `app_user`.
CREATE TABLE membership (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id  uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  user_id          uuid NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  role             membership_role NOT NULL DEFAULT 'member',
  status           membership_status NOT NULL DEFAULT 'invited',
  invited_by       uuid REFERENCES app_user (id) ON DELETE SET NULL,
  invited_at       timestamptz,
  accepted_at      timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organisation_id, user_id)
);

CREATE INDEX membership_user_id_idx ON membership (user_id);

-- Every organisation keeps at least one owner, so that nobody is ever locked
-- out of their own data.
CREATE UNIQUE INDEX membership_single_owner_idx
  ON membership (organisation_id)
  WHERE role = 'owner' AND status = 'active';

COMMENT ON INDEX membership_single_owner_idx IS
  'One active owner per organisation. Transferring ownership swaps the role in one statement.';

-- What an organisation is paying for. Seat and participant limits are read
-- from here; enforcing them is EXPD-069, and talking to Stripe is EXPD-068.
--
-- An organisation may have more than one row over time. The row that counts
-- is the one whose status is `trialing` or `active`.
CREATE TABLE subscription (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id         uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  -- The plan's own key, such as `school-annual`. The price lives in Stripe.
  plan_key                text NOT NULL CHECK (length(btrim(plan_key)) > 0),
  status                  subscription_status NOT NULL,
  stripe_customer_id      text,
  stripe_subscription_id  text,
  stripe_price_id         text,
  -- How many staff accounts the plan allows. NULL means no limit.
  seat_limit              integer CHECK (seat_limit IS NULL OR seat_limit > 0),
  -- How many students may play at once across the organisation's running
  -- sessions. NULL means no limit.
  participant_limit       integer CHECK (participant_limit IS NULL OR participant_limit > 0),
  -- How many expeditions may be held in `published` status. NULL means no limit.
  expedition_limit        integer CHECK (expedition_limit IS NULL OR expedition_limit > 0),
  trial_ends_at           timestamptz,
  current_period_start    timestamptz,
  current_period_end      timestamptz,
  cancel_at               timestamptz,
  cancelled_at            timestamptz,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT subscription_period_ordered CHECK (
    current_period_start IS NULL
    OR current_period_end IS NULL
    OR current_period_end > current_period_start
  )
);

CREATE UNIQUE INDEX subscription_stripe_subscription_id_key
  ON subscription (stripe_subscription_id)
  WHERE stripe_subscription_id IS NOT NULL;

CREATE INDEX subscription_organisation_id_idx ON subscription (organisation_id);

-- An organisation pays for one thing at a time. Older rows stay as history.
CREATE UNIQUE INDEX subscription_one_live_per_organisation_idx
  ON subscription (organisation_id)
  WHERE status IN ('trialing', 'active', 'past_due');

-- ---------------------------------------------------------------------------
-- Expeditions and their revisions
-- ---------------------------------------------------------------------------

-- One expedition, across every revision of it. The row holds the things that
-- do not change when an author publishes again: who owns it, who made it,
-- and whether it is still in use.
--
-- Everything an author can edit lives on `expedition_version`.
CREATE TABLE expedition (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id   uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  status            expedition_status NOT NULL DEFAULT 'draft',
  source            authoring_source NOT NULL DEFAULT 'studio',
  created_by        uuid REFERENCES app_user (id) ON DELETE SET NULL,
  updated_by        uuid REFERENCES app_user (id) ON DELETE SET NULL,
  archived_at       timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT expedition_archived_has_date
    CHECK ((status = 'archived') = (archived_at IS NOT NULL))
);

CREATE INDEX expedition_organisation_id_status_idx
  ON expedition (organisation_id, status);

COMMENT ON TABLE expedition IS
  'One expedition across every revision. The editable part is expedition_version.';

-- One revision of one expedition.
--
-- `definition` holds the whole EXPD-002 Expedition Definition document. It is
-- the source of truth. The mission and node tables below are a flat copy of
-- the parts other rows have to point at, written from this document by
-- EXPD-017 whenever the revision is saved.
--
-- A published revision is never edited. Publishing again writes a new row
-- with the next `definition_version`.
CREATE TABLE expedition_version (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id     uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  expedition_id       uuid NOT NULL REFERENCES expedition (id) ON DELETE CASCADE,
  -- Counts from one, and goes up by one on each publish. EXPD-017 owns it.
  definition_version  integer NOT NULL CHECK (definition_version > 0),
  -- The EXPD-002 schema version the document was written against, such as
  -- `1.0.0`. A reader checks this before reading the document.
  schema_version      text NOT NULL CHECK (schema_version ~ '^\d+\.\d+\.\d+$'),
  status              expedition_status NOT NULL DEFAULT 'draft',
  -- The whole Expedition Definition. Given this and the mission type
  -- registry, the engine can run the expedition without another query.
  definition          jsonb NOT NULL,
  -- Copied out of `definition.metadata` so that a list of expeditions can be
  -- drawn without opening every document. EXPD-017 writes both together.
  title               text NOT NULL CHECK (length(btrim(title)) > 0),
  summary             text NOT NULL DEFAULT '',
  locale              text NOT NULL DEFAULT 'en-GB',
  published_at        timestamptz,
  published_by        uuid REFERENCES app_user (id) ON DELETE SET NULL,
  created_by          uuid REFERENCES app_user (id) ON DELETE SET NULL,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  UNIQUE (expedition_id, definition_version),
  CONSTRAINT expedition_version_definition_is_object
    CHECK (jsonb_typeof(definition) = 'object'),
  -- A draft has not been published, and a published revision has a date.
  CONSTRAINT expedition_version_published_has_date
    CHECK ((status = 'published') = (published_at IS NOT NULL))
);

CREATE INDEX expedition_version_expedition_id_idx
  ON expedition_version (expedition_id, definition_version DESC);

CREATE INDEX expedition_version_organisation_id_idx
  ON expedition_version (organisation_id);

COMMENT ON COLUMN expedition_version.definition IS
  'The whole EXPD-002 Expedition Definition. Source of truth for this revision.';

-- ---------------------------------------------------------------------------
-- Mission types and templates
-- ---------------------------------------------------------------------------

-- One kind of task: scan a QR code, take a photo, solve a puzzle. The
-- registry (EXPD-009) reads these rows; this table only stores them.
--
-- A row with no `organisation_id` is a platform type every organisation can
-- use. A row with one is a type that organisation built in the Studio.
--
-- A type is never edited once published. A change means a new row with the
-- next `version`, so that an expedition pinned to the old one keeps working.
CREATE TABLE mission_type (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id    uuid REFERENCES organisation (id) ON DELETE CASCADE,
  -- The key an expedition pins to, such as `qr-hunt`.
  type_key           text NOT NULL CHECK (type_key ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  -- The version an expedition pins to, as three dot-separated numbers.
  version            text NOT NULL CHECK (version ~ '^\d+\.\d+\.\d+$'),
  name               text NOT NULL CHECK (length(btrim(name)) > 0),
  description        text NOT NULL DEFAULT '',
  status             mission_type_status NOT NULL DEFAULT 'draft',
  -- JSON Schema for `mission_instance.config`. Only the mission type knows
  -- the right shape for that object, so the check lives here (EXPD-009).
  config_schema      jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- JSON Schema for `submission.payload`.
  submission_schema  jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- What a new mission of this type starts out with in the Studio.
  default_config     jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- What the type needs from the student's device: `camera`, `location`,
  -- `qr`, `ar`, `microphone`. EXPD-009 gives the list its meaning.
  capabilities       text[] NOT NULL DEFAULT '{}',
  created_by         uuid REFERENCES app_user (id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mission_type_config_schema_is_object
    CHECK (jsonb_typeof(config_schema) = 'object'),
  CONSTRAINT mission_type_submission_schema_is_object
    CHECK (jsonb_typeof(submission_schema) = 'object'),
  CONSTRAINT mission_type_default_config_is_object
    CHECK (jsonb_typeof(default_config) = 'object')
);

-- A key and version are unique within an organisation, and unique again
-- across the platform types. Two indexes, because NULL is not equal to NULL.
CREATE UNIQUE INDEX mission_type_platform_key
  ON mission_type (type_key, version)
  WHERE organisation_id IS NULL;

CREATE UNIQUE INDEX mission_type_organisation_key
  ON mission_type (organisation_id, type_key, version)
  WHERE organisation_id IS NOT NULL;

COMMENT ON COLUMN mission_type.organisation_id IS
  'NULL means a platform type available to every organisation.';

-- A mission somebody already set up, ready to drop into an expedition. The
-- template set is EXPD-060 and EXPD-061; this table is where they go.
CREATE TABLE mission_template (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id  uuid REFERENCES organisation (id) ON DELETE CASCADE,
  mission_type_id  uuid NOT NULL REFERENCES mission_type (id) ON DELETE RESTRICT,
  name             text NOT NULL CHECK (length(btrim(name)) > 0),
  description      text NOT NULL DEFAULT '',
  status           mission_template_status NOT NULL DEFAULT 'draft',
  -- The configured settings, in the shape the mission type asks for. Copied
  -- into `mission_instance.config` when the template is used.
  config           jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- The EXPD-002 `MissionScoring` object the template suggests.
  scoring          jsonb NOT NULL DEFAULT '{}'::jsonb,
  subjects         text[] NOT NULL DEFAULT '{}',
  tags             text[] NOT NULL DEFAULT '{}',
  age_min          integer CHECK (age_min IS NULL OR age_min >= 0),
  age_max          integer CHECK (age_max IS NULL OR age_max >= 0),
  created_by       uuid REFERENCES app_user (id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mission_template_config_is_object
    CHECK (jsonb_typeof(config) = 'object'),
  CONSTRAINT mission_template_scoring_is_object
    CHECK (jsonb_typeof(scoring) = 'object'),
  CONSTRAINT mission_template_age_range_ordered
    CHECK (age_min IS NULL OR age_max IS NULL OR age_max >= age_min)
);

CREATE INDEX mission_template_organisation_id_idx ON mission_template (organisation_id);
CREATE INDEX mission_template_mission_type_id_idx ON mission_template (mission_type_id);
CREATE INDEX mission_template_tags_idx ON mission_template USING gin (tags);

COMMENT ON COLUMN mission_template.organisation_id IS
  'NULL means a platform template available to every organisation.';

-- ---------------------------------------------------------------------------
-- The contents of one revision: missions, nodes, hints
-- ---------------------------------------------------------------------------
--
-- These three tables are a flat copy of parts of
-- `expedition_version.definition`. They exist for two reasons, and for no
-- other: so that a runtime row can hold a real foreign key to the mission it
-- is about, and so that a query can find a mission without opening a JSONB
-- document. EXPD-017 writes them whenever it writes a version.
--
-- Each row keeps the id it has inside the document, in a `*_key` column. The
-- document's ids are strings and are only unique within one revision, so the
-- database gives every row its own uuid on top.

-- One mission placed in one revision of one expedition.
CREATE TABLE mission_instance (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id           uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  expedition_version_id     uuid NOT NULL REFERENCES expedition_version (id) ON DELETE CASCADE,
  -- The `MissionInstance.id` used inside the definition document.
  instance_key              text NOT NULL CHECK (length(btrim(instance_key)) > 0),

  -- What the document says the mission type is. These two are the record:
  -- they are copied straight from the document and never rewritten, so that
  -- a revision keeps pointing at the type version its author configured.
  mission_type_key          text NOT NULL,
  mission_type_version      text NOT NULL,
  -- The registry row those two resolve to, when the type is known here. A
  -- draft may name a type nobody has registered yet, so it may be NULL.
  mission_type_id           uuid REFERENCES mission_type (id) ON DELETE SET NULL,

  title                     text NOT NULL CHECK (length(btrim(title)) > 0),
  brief                     text NOT NULL DEFAULT '',
  instructions              text,

  -- The settings that belong to the mission type itself. A QR hunt keeps its
  -- codes in here, a puzzle keeps its answers. Deliberately opaque: only the
  -- mission type knows the right shape, so only EXPD-009 can check it.
  config                    jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- The EXPD-002 `MissionScoring` object: base points, partial credit, cap.
  scoring                   jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- Images, audio and video shown with the mission, as EXPD-002 `MediaRef`
  -- objects. Kept as an array because the document keeps their order.
  media                     jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- EXPD-002 `AttemptPolicy`. NULL max means there is no limit.
  max_attempts              integer CHECK (max_attempts IS NULL OR max_attempts > 0),
  cooldown_seconds          integer NOT NULL DEFAULT 0 CHECK (cooldown_seconds >= 0),
  -- How long a team has once it opens the mission. NULL means it is untimed.
  time_limit_seconds        integer CHECK (time_limit_seconds IS NULL OR time_limit_seconds > 0),
  verification              verification_mode NOT NULL DEFAULT 'automatic',

  -- EXPD-002 `LocationConstraint`, spread into columns so that a query can
  -- ask where a mission is. All four are set together or none of them are.
  location_latitude         double precision
    CHECK (location_latitude IS NULL OR location_latitude BETWEEN -90 AND 90),
  location_longitude        double precision
    CHECK (location_longitude IS NULL OR location_longitude BETWEEN -180 AND 180),
  location_radius_metres    double precision
    CHECK (location_radius_metres IS NULL OR location_radius_metres > 0),
  location_on_poor_accuracy poor_accuracy_action,

  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),

  UNIQUE (expedition_version_id, instance_key),
  CONSTRAINT mission_instance_config_is_object
    CHECK (jsonb_typeof(config) = 'object'),
  CONSTRAINT mission_instance_scoring_is_object
    CHECK (jsonb_typeof(scoring) = 'object'),
  CONSTRAINT mission_instance_media_is_array
    CHECK (jsonb_typeof(media) = 'array'),
  CONSTRAINT mission_instance_type_version_is_semver
    CHECK (mission_type_version ~ '^\d+\.\d+\.\d+$'),
  -- A location is given in full or not at all.
  CONSTRAINT mission_instance_location_all_or_nothing CHECK (
    num_nonnulls(
      location_latitude, location_longitude,
      location_radius_metres, location_on_poor_accuracy
    ) IN (0, 4)
  )
);

CREATE INDEX mission_instance_expedition_version_id_idx
  ON mission_instance (expedition_version_id);
CREATE INDEX mission_instance_mission_type_id_idx
  ON mission_instance (mission_type_id);
CREATE INDEX mission_instance_organisation_id_idx
  ON mission_instance (organisation_id);

COMMENT ON COLUMN mission_instance.config IS
  'Mission-type-specific settings. Shape owned by the mission type (EXPD-009).';

-- One stop in the expedition graph.
--
-- The edges between stops are not a table. They stay in
-- `expedition_version.definition`, where the engine already reads them, and a
-- copy of the ones leaving this stop is kept in `outgoing_edges` so that the
-- Studio can draw a node without loading the whole document. Nothing at
-- runtime points at an edge, which is why nothing needs one to have a key.
CREATE TABLE mission_node (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id        uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  expedition_version_id  uuid NOT NULL REFERENCES expedition_version (id) ON DELETE CASCADE,
  -- The `ExpeditionNode.id` used inside the definition document.
  node_key               text NOT NULL CHECK (length(btrim(node_key)) > 0),
  kind                   expedition_node_kind NOT NULL,
  -- A name for the author. Students never see it.
  title                  text NOT NULL DEFAULT '',
  notes                  text,
  -- Set when, and only when, the node holds a mission.
  mission_instance_id    uuid REFERENCES mission_instance (id) ON DELETE CASCADE,
  -- Shown to a team that reaches a finish node. NULL on every other kind.
  finish_message         text,
  -- Where the node sits on the Studio canvas (EXPD-026). No effect on play.
  layout_x               double precision,
  layout_y               double precision,
  -- The EXPD-002 `ExpeditionEdge` objects that leave this node, conditions
  -- included. A copy; the definition document is the source of truth.
  outgoing_edges         jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),

  UNIQUE (expedition_version_id, node_key),
  CONSTRAINT mission_node_edges_is_array
    CHECK (jsonb_typeof(outgoing_edges) = 'array'),
  CONSTRAINT mission_node_mission_kind_has_mission
    CHECK ((kind = 'mission') = (mission_instance_id IS NOT NULL)),
  CONSTRAINT mission_node_finish_message_only_on_finish
    CHECK (finish_message IS NULL OR kind = 'finish'),
  -- A finish node has nowhere to go, so it never carries an edge.
  CONSTRAINT mission_node_finish_has_no_edges
    CHECK (kind <> 'finish' OR outgoing_edges = '[]'::jsonb)
);

CREATE INDEX mission_node_expedition_version_id_idx
  ON mission_node (expedition_version_id);
CREATE INDEX mission_node_mission_instance_id_idx
  ON mission_node (mission_instance_id);

-- Exactly one start node per revision. EXPD-002 says so, and the database
-- says it again here, because a run with two starts cannot be played.
CREATE UNIQUE INDEX mission_node_single_start_idx
  ON mission_node (expedition_version_id)
  WHERE kind = 'start';

-- A mission is placed at exactly one node.
CREATE UNIQUE INDEX mission_node_one_node_per_mission_idx
  ON mission_node (mission_instance_id)
  WHERE mission_instance_id IS NOT NULL;

COMMENT ON COLUMN mission_node.outgoing_edges IS
  'Copy of the edges leaving this node. The definition document is the source of truth.';

-- One hint a team may spend a token on, copied from the mission's
-- `HintDefinition` list. Handing hints out and counting tokens is EXPD-046;
-- the tokens themselves are rows in `inventory_item`.
CREATE TABLE hint (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id      uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  mission_instance_id  uuid NOT NULL REFERENCES mission_instance (id) ON DELETE CASCADE,
  -- The `HintDefinition.id` used inside the definition document.
  hint_key             text NOT NULL CHECK (length(btrim(hint_key)) > 0),
  text                 text NOT NULL CHECK (length(btrim(text)) > 0),
  -- Hints are offered lowest first. Two hints on one mission never share it.
  display_order        integer NOT NULL CHECK (display_order >= 0),
  -- How many tokens this hint costs. Zero means it is free.
  token_cost           integer NOT NULL DEFAULT 1 CHECK (token_cost >= 0),
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE (mission_instance_id, hint_key),
  UNIQUE (mission_instance_id, display_order)
);

CREATE INDEX hint_mission_instance_id_idx ON hint (mission_instance_id);

-- ---------------------------------------------------------------------------
-- Running an expedition
-- ---------------------------------------------------------------------------

-- One run of one expedition with one group of students: a lesson, a school
-- trip, an open day.
--
-- A session pins the revision it runs. Publishing a new revision while a
-- session is going does not change what the students in it are playing.
--
-- `status` lists the states a run can be in. Which change may follow which,
-- and what pausing does to the clock, is EXPD-019 and EXPD-058.
CREATE TABLE expedition_session (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id        uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  expedition_id          uuid NOT NULL REFERENCES expedition (id) ON DELETE RESTRICT,
  -- The revision being played. RESTRICT, because a revision somebody has
  -- played must stay readable for as long as the results point at it.
  expedition_version_id  uuid NOT NULL REFERENCES expedition_version (id) ON DELETE RESTRICT,
  -- What the teacher calls this run, such as `Year 6 — Tuesday`.
  name                   text NOT NULL DEFAULT '',
  -- What students type to join (EXPD-018). Short, and not case sensitive.
  join_code              text NOT NULL CHECK (join_code ~ '^[A-Z0-9]{4,12}$'),
  status                 session_status NOT NULL DEFAULT 'scheduled',
  -- The teacher running it, and the one watching Director Mode (EXPD-055).
  host_user_id           uuid REFERENCES app_user (id) ON DELETE SET NULL,
  scheduled_start_at     timestamptz,
  started_at             timestamptz,
  -- When the current pause began. NULL while the run is not paused.
  paused_at              timestamptz,
  -- How long the run has spent paused so far, so that a team's clock can be
  -- worked out without replaying every pause (EXPD-058).
  paused_seconds_total   integer NOT NULL DEFAULT 0 CHECK (paused_seconds_total >= 0),
  ended_at               timestamptz,
  created_by             uuid REFERENCES app_user (id) ON DELETE SET NULL,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT expedition_session_paused_has_time
    CHECK ((status = 'paused') = (paused_at IS NOT NULL)),
  CONSTRAINT expedition_session_ended_has_time
    CHECK ((status IN ('ended', 'cancelled')) = (ended_at IS NOT NULL)),
  CONSTRAINT expedition_session_times_ordered
    CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at)
);

-- A join code only has to be unique among the runs a student could join
-- right now. Once a run ends its code goes back in the pool.
CREATE UNIQUE INDEX expedition_session_live_join_code_idx
  ON expedition_session (join_code)
  WHERE status IN ('scheduled', 'lobby', 'running', 'paused');

CREATE INDEX expedition_session_organisation_id_status_idx
  ON expedition_session (organisation_id, status);
CREATE INDEX expedition_session_expedition_id_idx ON expedition_session (expedition_id);
CREATE INDEX expedition_session_expedition_version_id_idx
  ON expedition_session (expedition_version_id);

COMMENT ON INDEX expedition_session_live_join_code_idx IS
  'Join codes are unique among joinable runs only, so codes can be reused later.';

-- One student in one run.
--
-- A participant is not an `app_user`. Most students never have an account:
-- they type a join code and a first name and start playing. `user_id` is
-- there for the case where somebody joining does have one.
--
-- There is deliberately no email, date of birth or any other contact detail
-- on this table. What may be collected about a child is EXPD-071.
CREATE TABLE participant (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id         uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  expedition_session_id   uuid NOT NULL REFERENCES expedition_session (id) ON DELETE CASCADE,
  -- Set only when the person joining already has an account.
  user_id                 uuid REFERENCES app_user (id) ON DELETE SET NULL,
  -- The name shown to the rest of the team. Usually a first name.
  display_name            text NOT NULL CHECK (length(btrim(display_name)) > 0),
  status                  participant_status NOT NULL DEFAULT 'joined',
  -- Identifies the phone, so that a student who closes the app can come back
  -- to the same place. Not a person, and not shared between runs.
  device_id               text,
  joined_at               timestamptz NOT NULL DEFAULT now(),
  last_seen_at            timestamptz,
  left_at                 timestamptz,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX participant_expedition_session_id_idx
  ON participant (expedition_session_id, status);
CREATE INDEX participant_user_id_idx ON participant (user_id);

-- One account joins one run once.
CREATE UNIQUE INDEX participant_session_user_idx
  ON participant (expedition_session_id, user_id)
  WHERE user_id IS NOT NULL;

COMMENT ON TABLE participant IS
  'A student in one run. Not an account: most students play without one.';

-- One team in one run. Teams are what score; a participant on their own
-- never does.
CREATE TABLE team (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id         uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  expedition_session_id   uuid NOT NULL REFERENCES expedition_session (id) ON DELETE CASCADE,
  name                    text NOT NULL CHECK (length(btrim(name)) > 0),
  status                  team_status NOT NULL DEFAULT 'forming',
  -- Where the team is in the graph. NULL until the run starts.
  current_node_id         uuid REFERENCES mission_node (id) ON DELETE SET NULL,
  -- The team's running total. `score_event` is the record of how it got
  -- there; this column is a total kept alongside it so that a leaderboard
  -- does not have to add up the stream on every read (EXPD-022).
  total_score             integer NOT NULL DEFAULT 0,
  -- Hint tokens left. EXPD-046 hands them out; the matching
  -- `inventory_item` row is the auditable record.
  hint_tokens_remaining   integer NOT NULL DEFAULT 0 CHECK (hint_tokens_remaining >= 0),
  started_at              timestamptz,
  finished_at             timestamptz,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  UNIQUE (expedition_session_id, name),
  CONSTRAINT team_times_ordered
    CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at)
);

CREATE INDEX team_expedition_session_id_idx ON team (expedition_session_id);
CREATE INDEX team_current_node_id_idx ON team (current_node_id);
-- Draws a leaderboard for one run in one index scan.
CREATE INDEX team_leaderboard_idx
  ON team (expedition_session_id, total_score DESC, finished_at ASC);

COMMENT ON COLUMN team.total_score IS
  'Kept total. score_event is the authoritative record (EXPD-014).';

-- Which students are on which team, and what each of them is doing.
CREATE TABLE team_member (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id  uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  team_id          uuid NOT NULL REFERENCES team (id) ON DELETE CASCADE,
  participant_id   uuid NOT NULL REFERENCES participant (id) ON DELETE CASCADE,
  -- One of the role names the expedition's `TeamRules.roles` lists, such as
  -- `navigator`. Free text, because the author chooses the names. NULL means
  -- the expedition uses no roles, or none has been handed out yet.
  role             text,
  -- The member who speaks for the team. At most one per team.
  is_leader        boolean NOT NULL DEFAULT false,
  joined_at        timestamptz NOT NULL DEFAULT now(),
  left_at          timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (team_id, participant_id)
);

CREATE INDEX team_member_team_id_idx ON team_member (team_id);
CREATE INDEX team_member_participant_id_idx ON team_member (participant_id);

-- A student is on one team at a time within a run. Enforced across teams by
-- the partial index below, which only counts members who have not left.
CREATE UNIQUE INDEX team_member_one_team_per_participant_idx
  ON team_member (participant_id)
  WHERE left_at IS NULL;

CREATE UNIQUE INDEX team_member_single_leader_idx
  ON team_member (team_id)
  WHERE is_leader AND left_at IS NULL;

-- ---------------------------------------------------------------------------
-- Playing a mission
-- ---------------------------------------------------------------------------

-- One try at one mission by one team.
--
-- A team that gets a puzzle wrong twice and right on the third go has three
-- rows here. `attempt_number` counts them from one, and the mission's
-- `max_attempts` is the largest it may reach.
--
-- `status` lists the states a try can be in. The order they may be visited
-- in is the mission state machine, which is EXPD-010.
CREATE TABLE mission_attempt (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id         uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  expedition_session_id   uuid NOT NULL REFERENCES expedition_session (id) ON DELETE CASCADE,
  team_id                 uuid NOT NULL REFERENCES team (id) ON DELETE CASCADE,
  -- RESTRICT: a mission that has been attempted cannot be deleted out from
  -- under the attempt. This also stops a played revision being removed.
  mission_instance_id     uuid NOT NULL REFERENCES mission_instance (id) ON DELETE RESTRICT,
  -- Who opened it. NULL when the team opened it together, or is unknown.
  opened_by               uuid REFERENCES participant (id) ON DELETE SET NULL,
  attempt_number          integer NOT NULL CHECK (attempt_number > 0),
  status                  attempt_status NOT NULL DEFAULT 'open',
  started_at              timestamptz NOT NULL DEFAULT now(),
  -- When the mission's own time limit runs out. NULL when it is untimed.
  deadline_at             timestamptz,
  completed_at            timestamptz,
  -- What this try was finally worth, once scoring has run. NULL until then.
  -- The `score_event` rows are the record of how it adds up.
  awarded_points          integer,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  UNIQUE (team_id, mission_instance_id, attempt_number),
  CONSTRAINT mission_attempt_completed_after_start
    CHECK (completed_at IS NULL OR completed_at >= started_at),
  CONSTRAINT mission_attempt_deadline_after_start
    CHECK (deadline_at IS NULL OR deadline_at > started_at),
  -- A try that is still going has not been settled.
  CONSTRAINT mission_attempt_settled_has_completed_at CHECK (
    status IN ('open', 'submitted', 'awaiting-review')
    = (completed_at IS NULL)
  )
);

CREATE INDEX mission_attempt_team_id_idx ON mission_attempt (team_id, status);
CREATE INDEX mission_attempt_mission_instance_id_idx
  ON mission_attempt (mission_instance_id);
CREATE INDEX mission_attempt_session_status_idx
  ON mission_attempt (expedition_session_id, status);
-- Finds the tries a teacher still has to look at (EXPD-056).
CREATE INDEX mission_attempt_awaiting_review_idx
  ON mission_attempt (expedition_session_id, started_at)
  WHERE status = 'awaiting-review';

-- What a team handed in for one try.
--
-- A try normally has one submission. It can have more than one when the
-- mission lets a team add to its answer, or when a queued offline submission
-- arrives after the team has already sent something (EXPD-048).
CREATE TABLE submission (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id     uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  mission_attempt_id  uuid NOT NULL REFERENCES mission_attempt (id) ON DELETE CASCADE,
  -- Who pressed send. NULL when it is not known which member did.
  participant_id      uuid REFERENCES participant (id) ON DELETE SET NULL,
  -- The answer itself, in whatever shape the mission type asks for: a scanned
  -- code, a typed answer, the ids of the photos taken. Checked against the
  -- type's `submission_schema` by EXPD-011.
  payload             jsonb NOT NULL DEFAULT '{}'::jsonb,
  status              submission_status NOT NULL DEFAULT 'pending',
  -- Handed in after the expedition's time limit. What that costs is the late
  -- policy in the expedition's rules.
  is_late             boolean NOT NULL DEFAULT false,
  -- When the student's device recorded it, which is not when the server got
  -- it if the phone had no signal (EXPD-048).
  submitted_at        timestamptz NOT NULL DEFAULT now(),
  received_at         timestamptz NOT NULL DEFAULT now(),
  reviewed_at         timestamptz,
  reviewed_by         uuid REFERENCES app_user (id) ON DELETE SET NULL,
  review_note         text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT submission_payload_is_object
    CHECK (jsonb_typeof(payload) = 'object'),
  CONSTRAINT submission_reviewed_has_decision
    CHECK ((status IN ('accepted', 'rejected')) OR reviewed_at IS NULL)
);

CREATE INDEX submission_mission_attempt_id_idx ON submission (mission_attempt_id);
CREATE INDEX submission_participant_id_idx ON submission (participant_id);
-- The review queue for one organisation, oldest first (EXPD-056).
CREATE INDEX submission_review_queue_idx
  ON submission (organisation_id, submitted_at)
  WHERE status IN ('pending', 'needs-review');

COMMENT ON COLUMN submission.payload IS
  'The answer, in the shape the mission type defines. Checked by EXPD-011.';

-- ---------------------------------------------------------------------------
-- Media
-- ---------------------------------------------------------------------------

-- One file in Azure Blob Storage: a cover image, a mission photo, a piece of
-- evidence a team handed in.
--
-- The row never holds a URL. A URL is signed when it is asked for (EXPD-021)
-- and would go stale if it were written down here.
--
-- A row is written before the file exists, because the student's phone
-- uploads straight to the signed URL. `status` says whether the file has
-- actually arrived.
CREATE TABLE media_asset (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id    uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  kind               media_kind NOT NULL,
  status             media_status NOT NULL DEFAULT 'pending',
  -- Where the bytes are. Container and path together, never a URL.
  storage_container  text NOT NULL CHECK (length(btrim(storage_container)) > 0),
  storage_path       text NOT NULL CHECK (length(btrim(storage_path)) > 0),
  content_type       text,
  byte_size          bigint CHECK (byte_size IS NULL OR byte_size >= 0),
  -- Set on images and video, so that a layout can leave the right gap before
  -- the file has loaded.
  width_px           integer CHECK (width_px IS NULL OR width_px > 0),
  height_px          integer CHECK (height_px IS NULL OR height_px > 0),
  duration_seconds   integer CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
  checksum_sha256    text CHECK (checksum_sha256 IS NULL OR checksum_sha256 ~ '^[a-f0-9]{64}$'),
  -- Read aloud by a screen reader in place of the file.
  alt_text           text,
  -- Set on a file in an expedition's own library (EXPD-030).
  expedition_id      uuid REFERENCES expedition (id) ON DELETE SET NULL,
  -- Set on evidence a team handed in. SET NULL rather than CASCADE, because
  -- the blob outlives the row and still has to be tidied up afterwards.
  submission_id      uuid REFERENCES submission (id) ON DELETE SET NULL,
  uploaded_by        uuid REFERENCES app_user (id) ON DELETE SET NULL,
  -- Set on evidence, where the uploader is a student and not an account.
  uploaded_by_participant uuid REFERENCES participant (id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (storage_container, storage_path)
);

CREATE INDEX media_asset_organisation_id_idx ON media_asset (organisation_id, kind);
CREATE INDEX media_asset_expedition_id_idx ON media_asset (expedition_id);
CREATE INDEX media_asset_submission_id_idx ON media_asset (submission_id);
-- Finds rows whose upload never finished, so they can be cleared out.
CREATE INDEX media_asset_pending_idx
  ON media_asset (created_at)
  WHERE status = 'pending';

-- ---------------------------------------------------------------------------
-- Rewards, markers and assets
-- ---------------------------------------------------------------------------

-- A badge a team or a student can earn: `first-to-finish`, `no-hints-used`.
--
-- This table holds what a badge *is*. Earning one is recorded as an
-- `inventory_item` row of kind `badge` pointing back at it, so that an award
-- sits in the same place as everything else a team holds.
CREATE TABLE badge (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id  uuid REFERENCES organisation (id) ON DELETE CASCADE,
  badge_key        text NOT NULL CHECK (badge_key ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  name             text NOT NULL CHECK (length(btrim(name)) > 0),
  description      text NOT NULL DEFAULT '',
  icon_media_id    uuid REFERENCES media_asset (id) ON DELETE SET NULL,
  -- What has to be true to earn it. Read by whatever awards badges; this
  -- table does not say what the shape means.
  criteria         jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT badge_criteria_is_object CHECK (jsonb_typeof(criteria) = 'object')
);

CREATE UNIQUE INDEX badge_platform_key
  ON badge (badge_key)
  WHERE organisation_id IS NULL;

CREATE UNIQUE INDEX badge_organisation_key
  ON badge (organisation_id, badge_key)
  WHERE organisation_id IS NOT NULL;

COMMENT ON TABLE badge IS
  'What a badge is. Earning one is an inventory_item row of kind badge.';

-- A 3D model, an image target or an effect used by an AR mission
-- (EXPD-072, EXPD-073).
CREATE TABLE ar_asset (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id  uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  asset_key        text NOT NULL CHECK (length(btrim(asset_key)) > 0),
  name             text NOT NULL CHECK (length(btrim(name)) > 0),
  kind             ar_asset_kind NOT NULL,
  -- The file itself, when the asset has one. An anchor or an effect may be
  -- described entirely by the two JSONB columns below and have no file.
  media_asset_id   uuid REFERENCES media_asset (id) ON DELETE SET NULL,
  -- `glb`, `usdz`, `reality`. Which ones a phone can open is EXPD-073.
  source_format    text,
  -- Where the asset sits relative to its anchor: position, rotation, scale.
  transform        jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- What it does once placed: an animation to play, a tap to respond to.
  behaviour        jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by       uuid REFERENCES app_user (id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organisation_id, asset_key),
  CONSTRAINT ar_asset_transform_is_object
    CHECK (jsonb_typeof(transform) = 'object'),
  CONSTRAINT ar_asset_behaviour_is_object
    CHECK (jsonb_typeof(behaviour) = 'object')
);

CREATE INDEX ar_asset_media_asset_id_idx ON ar_asset (media_asset_id);

-- One printed QR code, and what scanning it means (EXPD-032, EXPD-043).
--
-- A marker may belong to a mission, or it may be a code an organisation has
-- printed and can point at whichever mission it likes.
CREATE TABLE qr_marker (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id        uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  -- What the printed code actually encodes. Unique within an organisation,
  -- so that a scan resolves to exactly one marker.
  code                   text NOT NULL CHECK (length(btrim(code)) > 0),
  -- What a person should write on the sign, such as `Library window`.
  label                  text NOT NULL DEFAULT '',
  status                 qr_marker_status NOT NULL DEFAULT 'active',
  expedition_version_id  uuid REFERENCES expedition_version (id) ON DELETE CASCADE,
  mission_instance_id    uuid REFERENCES mission_instance (id) ON DELETE CASCADE,
  -- Where the code is stuck up, when that is known.
  latitude               double precision CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  longitude              double precision CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  metadata               jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by             uuid REFERENCES app_user (id) ON DELETE SET NULL,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organisation_id, code),
  CONSTRAINT qr_marker_metadata_is_object
    CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT qr_marker_location_all_or_nothing
    CHECK (num_nonnulls(latitude, longitude) IN (0, 2))
);

CREATE INDEX qr_marker_mission_instance_id_idx ON qr_marker (mission_instance_id);
CREATE INDEX qr_marker_expedition_version_id_idx ON qr_marker (expedition_version_id);

-- Something a team or a student is holding during a run: hint tokens, a
-- badge they have earned, an item a mission gave them.
--
-- A row belongs to a team, and may narrow to one member of it.
CREATE TABLE inventory_item (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id        uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  expedition_session_id  uuid NOT NULL REFERENCES expedition_session (id) ON DELETE CASCADE,
  team_id                uuid NOT NULL REFERENCES team (id) ON DELETE CASCADE,
  -- Set when the item belongs to one member rather than the whole team.
  participant_id         uuid REFERENCES participant (id) ON DELETE CASCADE,
  kind                   inventory_item_kind NOT NULL,
  -- What the item is, within its kind: `hint-token`, `museum-key`. For a
  -- badge it is the badge's own key.
  item_key               text NOT NULL CHECK (length(btrim(item_key)) > 0),
  name                   text NOT NULL DEFAULT '',
  quantity               integer NOT NULL DEFAULT 1 CHECK (quantity >= 0),
  -- Set when, and only when, the item is an earned badge.
  badge_id               uuid REFERENCES badge (id) ON DELETE SET NULL,
  -- Which mission gave it out, when one did.
  mission_instance_id    uuid REFERENCES mission_instance (id) ON DELETE SET NULL,
  metadata               jsonb NOT NULL DEFAULT '{}'::jsonb,
  acquired_at            timestamptz NOT NULL DEFAULT now(),
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT inventory_item_metadata_is_object
    CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT inventory_item_badge_kind_has_badge
    CHECK (kind <> 'badge' OR badge_id IS NOT NULL)
);

CREATE INDEX inventory_item_team_id_idx ON inventory_item (team_id, kind);
CREATE INDEX inventory_item_participant_id_idx ON inventory_item (participant_id);
CREATE INDEX inventory_item_expedition_session_id_idx ON inventory_item (expedition_session_id);

-- A team holds one row per item it owns, and a member holds one row per item
-- of their own. Two indexes, because NULL is not equal to NULL.
CREATE UNIQUE INDEX inventory_item_team_key_idx
  ON inventory_item (team_id, item_key)
  WHERE participant_id IS NULL;

CREATE UNIQUE INDEX inventory_item_participant_key_idx
  ON inventory_item (team_id, participant_id, item_key)
  WHERE participant_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Event streams
-- ---------------------------------------------------------------------------
--
-- The three tables below are append-only. A row is written once and never
-- changed, which is why none of them has an `updated_at` column or an update
-- trigger. Making that a rule the database enforces is EXPD-014 for scores
-- and EXPD-006 for the audit log.

-- Every time a team's score moved, and why.
--
-- This is the record. `team.total_score` is a total kept alongside it for
-- speed, and can always be rebuilt by adding up a team's rows here.
CREATE TABLE score_event (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id        uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  expedition_session_id  uuid NOT NULL REFERENCES expedition_session (id) ON DELETE CASCADE,
  team_id                uuid NOT NULL REFERENCES team (id) ON DELETE CASCADE,
  -- Set when one member's action caused it.
  participant_id         uuid REFERENCES participant (id) ON DELETE SET NULL,
  reason                 score_event_reason NOT NULL,
  -- Positive for points earned, negative for points taken away.
  points                 integer NOT NULL,
  -- What the points were for, as much of it as is known.
  mission_instance_id    uuid REFERENCES mission_instance (id) ON DELETE SET NULL,
  mission_attempt_id     uuid REFERENCES mission_attempt (id) ON DELETE SET NULL,
  submission_id          uuid REFERENCES submission (id) ON DELETE SET NULL,
  hint_id                uuid REFERENCES hint (id) ON DELETE SET NULL,
  -- The `ScoringRule.id` from the definition document, when a rule caused
  -- this. A string, because the rule lives inside the document.
  scoring_rule_key       text,
  -- Set when a teacher adjusted the score by hand (EXPD-058).
  created_by             uuid REFERENCES app_user (id) ON DELETE SET NULL,
  -- Why, in the teacher's own words, on a manual adjustment.
  note                   text,
  metadata               jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at            timestamptz NOT NULL DEFAULT now(),
  created_at             timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT score_event_metadata_is_object
    CHECK (jsonb_typeof(metadata) = 'object'),
  -- A hand adjustment says who made it. Everything else is the engine.
  CONSTRAINT score_event_manual_has_author
    CHECK (reason <> 'manual-adjustment' OR created_by IS NOT NULL)
);

-- Adds up one team's score, and draws a team's own history in order.
CREATE INDEX score_event_team_id_occurred_at_idx
  ON score_event (team_id, occurred_at);
CREATE INDEX score_event_session_occurred_at_idx
  ON score_event (expedition_session_id, occurred_at);
CREATE INDEX score_event_mission_attempt_id_idx ON score_event (mission_attempt_id);

COMMENT ON TABLE score_event IS
  'Append-only record of every score change. Authoritative; team.total_score is a cache.';

-- Something that happened during a run, in the order it happened.
--
-- This is what the realtime channel sends (EXPD-023) and what Director Mode
-- replays when a teacher opens the dashboard part way through (EXPD-055).
--
-- `type` is text rather than an enum because the list of event names belongs
-- to EXPD-023 and EXPD-057, and will grow as features land. A new name must
-- not need a migration.
CREATE TABLE live_event (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Orders events across the whole platform, and gives a client something to
  -- ask for more from after a dropped connection.
  sequence               bigint GENERATED ALWAYS AS IDENTITY,
  organisation_id        uuid NOT NULL REFERENCES organisation (id) ON DELETE CASCADE,
  expedition_session_id  uuid NOT NULL REFERENCES expedition_session (id) ON DELETE CASCADE,
  -- Set when the event is about one team, or one student, rather than the
  -- whole run.
  team_id                uuid REFERENCES team (id) ON DELETE CASCADE,
  participant_id         uuid REFERENCES participant (id) ON DELETE SET NULL,
  -- What happened, such as `team.joined` or `mission.completed`. The names
  -- are EXPD-023's to define.
  type                   text NOT NULL CHECK (length(btrim(type)) > 0),
  payload                jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- Set when a teacher caused it by hand (EXPD-057).
  created_by             uuid REFERENCES app_user (id) ON DELETE SET NULL,
  occurred_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT live_event_payload_is_object CHECK (jsonb_typeof(payload) = 'object')
);

CREATE UNIQUE INDEX live_event_sequence_key ON live_event (sequence);
-- Catches a client up from where it dropped.
CREATE INDEX live_event_session_sequence_idx
  ON live_event (expedition_session_id, sequence);
CREATE INDEX live_event_team_id_idx ON live_event (team_id, sequence);

COMMENT ON COLUMN live_event.type IS
  'Event name. Text rather than an enum: the vocabulary is EXPD-023 and EXPD-057.';

-- Who did what, to what, and when (EXPD-006).
--
-- The log outlives the rows it describes, so every reference out of it is
-- nullable and set to NULL rather than deleted. `entity_id` is a plain uuid
-- with no foreign key for the same reason: an entry about a deleted
-- expedition is exactly the entry somebody will want to read.
CREATE TABLE audit_log (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sequence             bigint GENERATED ALWAYS AS IDENTITY,
  -- NULL on a platform-level action that belongs to no organisation.
  organisation_id      uuid REFERENCES organisation (id) ON DELETE SET NULL,
  actor_kind           audit_actor_kind NOT NULL,
  actor_user_id        uuid REFERENCES app_user (id) ON DELETE SET NULL,
  actor_participant_id uuid REFERENCES participant (id) ON DELETE SET NULL,
  -- Kept even after the account is gone, so the entry still names somebody.
  actor_label          text NOT NULL DEFAULT '',
  -- What was done, such as `expedition.published` or `submission.rejected`.
  action               text NOT NULL CHECK (length(btrim(action)) > 0),
  -- What it was done to: the table name, and the row's id.
  entity_type          text NOT NULL CHECK (length(btrim(entity_type)) > 0),
  entity_id            uuid,
  -- What changed. EXPD-006 decides how much of a row goes in here, and what
  -- has to be left out of it (EXPD-071).
  changes              jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- Where the request came from.
  ip_address           inet,
  user_agent           text,
  -- Ties an entry to one API request, so a whole request reads as one story.
  request_id           text,
  occurred_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_changes_is_object
    CHECK (jsonb_typeof(changes) = 'object'),
  CONSTRAINT audit_log_user_actor_has_user
    CHECK (actor_kind <> 'user' OR actor_user_id IS NOT NULL),
  CONSTRAINT audit_log_participant_actor_has_participant
    CHECK (actor_kind <> 'participant' OR actor_participant_id IS NOT NULL)
);

CREATE UNIQUE INDEX audit_log_sequence_key ON audit_log (sequence);
CREATE INDEX audit_log_organisation_occurred_at_idx
  ON audit_log (organisation_id, occurred_at DESC);
CREATE INDEX audit_log_entity_idx ON audit_log (entity_type, entity_id, occurred_at DESC);
CREATE INDEX audit_log_actor_user_id_idx ON audit_log (actor_user_id, occurred_at DESC);
CREATE INDEX audit_log_request_id_idx ON audit_log (request_id) WHERE request_id IS NOT NULL;

COMMENT ON TABLE audit_log IS
  'Append-only. Outlives the rows it describes, so entity_id has no foreign key.';

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------
--
-- One trigger per table that has an `updated_at` column, so that no caller
-- can forget to set it. The three append-only event tables are not listed,
-- because nothing ever updates them.

DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'organisation', 'app_user', 'membership', 'subscription',
    'expedition', 'expedition_version',
    'mission_type', 'mission_template',
    'mission_instance', 'mission_node', 'hint',
    'expedition_session', 'participant', 'team', 'team_member',
    'mission_attempt', 'submission',
    'media_asset', 'badge', 'ar_asset', 'qr_marker', 'inventory_item'
  ] LOOP
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE UPDATE ON %I '
      'FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
      table_name || '_set_updated_at',
      table_name
    );
  END LOOP;
END;
$$;

COMMIT;
